# Generated by Django 2.0 on 2018-08-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fileid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
