# Generated by Django 2.0 on 2018-08-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0002_auto_20180807_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='epub',
            new_name='ppub',
        ),
    ]
