# Generated by Django 2.0 on 2018-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0003_auto_20180807_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
