# Generated by Django 2.0 on 2018-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0004_auto_20180807_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fileid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
