# Generated by Django 2.0 on 2018-08-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0006_auto_20180807_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
