# Generated by Django 2.0 on 2018-08-08 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0011_auto_20180808_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngram1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngram1Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Article')),
                ('ngram1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Ngram1')),
            ],
        ),
        migrations.CreateModel(
            name='Ngram2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngram2Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Article')),
                ('ngram2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Ngram2')),
            ],
        ),
        migrations.CreateModel(
            name='Ngram3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ngram3Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Article')),
                ('ngram3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdh_corpus.Ngram3')),
            ],
        ),
        migrations.RemoveField(
            model_name='ngramarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ngramarticle',
            name='ngram',
        ),
        migrations.DeleteModel(
            name='Ngram',
        ),
        migrations.DeleteModel(
            name='NgramArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='domains',
            field=models.ManyToManyField(to='mdh_corpus.Domain'),
        ),
    ]
