# Generated by Django 2.0 on 2018-08-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0012_auto_20180808_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
