# Generated by Django 2.0 on 2018-08-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0015_auto_20180811_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngram1article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ngram1article',
            name='ngram1',
        ),
        migrations.RemoveField(
            model_name='ngram2article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ngram2article',
            name='ngram2',
        ),
        migrations.RemoveField(
            model_name='ngram3article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='ngram3article',
            name='ngram3',
        ),
        migrations.DeleteModel(
            name='Ngram1',
        ),
        migrations.DeleteModel(
            name='Ngram1Article',
        ),
        migrations.DeleteModel(
            name='Ngram2',
        ),
        migrations.DeleteModel(
            name='Ngram2Article',
        ),
        migrations.DeleteModel(
            name='Ngram3',
        ),
        migrations.DeleteModel(
            name='Ngram3Article',
        ),
    ]
