# Generated by Django 2.0 on 2018-08-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdh_corpus', '0016_auto_20180811_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article3term',
            options={'managed': False},
        ),
    ]
